### ISSUE TITLE
Flagging a Submission should immediately close Grading.

### ISSUE THREAD

**Issue by teiknsmith** [natecraddock/zygrader#19]
When a TA flags a submission, they are almost certainly intending to close the lab and leave it for someone else (the Head TA). We can save a few keypresses and make the workflow more intuitive by automatically closing the grading dialog after a flag is created.

As is, some TAs get confused about whether or not they actually created a flag after using the flag option.

**Comment by natecraddock** [comment]
We might be able to get this working in the current code (probably a bit hacky), but the new windowing system will have this as a feature

**Comment by SeaSaltTree** [comment]
I'm trying to take a look at this. I still am experiencing a crash whenever I try to open a popup in grading or emails though.

**Comment by natecraddock** [comment]
@SeaSaltTree Is this crash related to fixing this issue? If not, make sure you pull in the latest changes in master

Feel free to post crash info on discord if you need help debugging it

**Comment by SeaSaltTree** [comment]
@natecraddock Yes and no. I mostly spent my time getting more acquainted with the zygrader code and how it flags things. I was hoping though that I could open the Grading popup to see what it looks like and what the options on the popup look like to get a better idea of how the window closes, flags, etc. I'm pretty sure I have pulled in the latest changes. I'm on the 5.0 version. Is it crashing for you? If it's just me, then it must be on my end. I wasn't sure because the other day when it happened, I thought it was just because the popups hadn't been added.

**Comment by natecraddock** [comment]
The version should still be 5.0.0. If you do `git log` you should see the most recent commit is d63e09ddcd05c. If not, then pull in the latest changes. I did fix the crash so the grading popup should work for you too.

**Comment by natecraddock** [comment]
There is one other place in the UI where we want this behavior. In Admin > Class Management > Lab Manager > Edit Current Labs > (pick lab) > Remove. Clicking remove should close the editing popup.

This should be the same code as is needed for closing the grade popup after flagging.

**Comment by natecraddock** [comment]
Closed by 05ee981fbf
