### ISSUE TITLE
Add ability to look at flagged submission without deleting

### ISSUE THREAD

**Issue by derekanderson98** [natecraddock/zygrader#30]
Currently, looking at a flagged submission deletes the flag. This assumes that one looking at a flagged submission is immediately capable of grading it, or the flag is no longer necessary for some other reason. While yes, in a lot of cases the flag is no longer needed, being able to view an assignment without unflagging would be helpful in some cases, such as to see if a student with an extension has submitted yet.

**Comment by natecraddock** [comment]
I agree that this should be resolved. I see two possible routes of implementation.

### Options Popup
The `Submission Flagged` popup allows unflagging, or exiting. We could replace this with an Options Popup with 3 options: `Close`, `Unflag`, `View`. 

### Unflag Option
Rather than showing a popup that needs confirmation before viewing a flagged student we could simply always allow viewing students, and replace the `Flag` entry on the options row with `Unflag`. Before the student is viewed a simple popup could open with the flag message, requiring the user to press `Enter`

**Comment by natecraddock** [comment]
Either way we go with this, it is dependent on the window manager refactor #28 It could be solved in master, but since the refactor will be ready to go next week I would rather wait until then.

**Comment by natecraddock** [comment]
Talking with @seyfdall We decided to go with the first option to add more options to the popup.
