### ISSUE TITLE
Default Directory

### ISSUE THREAD

**Issue by easton873** [natecraddock/zygrader#33]
In preferences can you add a default directory that can be changed to whatever directory the user wants it to be?  This really only applies for the grade puller and isn't really an issue, just a question of how difficult it would be to add.

**Comment by natecraddock** [comment]
I think we could expand this to be more general because there are a few other cases where we output files and could use a default output directory. We output executables for running code, and we output a `HotPlate.csv` file or any other output from code.

I think the default could be `~`, and we could allow setting it from the preferences to any valid directory.
