### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by natecraddock** [natecraddock/zygrader#5]
I haven't run zygrader directly on my machine since March. In the time between, it has been multi threaded. Likely one of those threads is causing very high CPU usage.

**Comment by teiknsmith** [comment]
In `window.py` line 214, we can set `nodelay` on the `input_win` to `False` instead of `True` - I just tried this and it dropped the CPU usage to ~0% in idle and I could only get it to reach ~25% with heavy input.

I see the comment on line 104 of the same file, which raises concern with pushing an immediate fix, but I did not experience any exceptions, so I think this should work. This comment was probably from when we used `getkey` instead of `getch` - which according to the docs does have this issue (but `getch` does not).

**Comment by natecraddock** [comment]
Okay, that makes a lot of sense. I can commit the fix later this afternoon, but if you want to do it before then go ahead.
