### ISSUE TITLE
Creating local dirs

### ISSUE THREAD

**Issue by teiknsmith** [natecraddock/zygrader#72]
When running zygrader, it creates `.locks` and `log` directories in whatever directory was the current working directory when zygrader started.

**Comment by natecraddock** [comment]
I can't replicate this consistently, but I'll investigate.

**Comment by teiknsmith** [comment]
It might have something to do with what semester is chosen or switching between semesters. Iirc, I switched class overrides around when this happened.

**Comment by natecraddock** [comment]
I have tried switching semesters (in the overrides), ssh, Ubuntu 20.04, and I still cannot replicate this. I do know it happens because today I signed in and noticed the two directories had been created, with the `log.txt` containing a log from yesterday (Jan 27)

Based on the the code, the log directory shouldn't be created anywhere besides the shared folder, unless `CLASS_DIRECTORY` wasn't setup correctly for some bizarre reason. I'll keep looking, but I don't think this is super high priority to keep actively investigating.

**Comment by teiknsmith** [comment]
while I was working on Bob's Shake, I got this again - and I'm fairly certain it happened because of an issue in starting up. in one instance of trying to start zygrader, it was taking a long time (I think because of the system delays that have been happening more frequently recently), and so I killed the process (ctrl+c), and shortly after this I noticed a log folder.

**Comment by natecraddock** [comment]
I just checked this again and I had the two folders again created on the 4th of February.

Also, I think I figured out the issue. Will investigate today, but it is _very_ likely as you suggested, when zygrader terminates unexpectedly on startup.

**Comment by derekanderson98** [comment]
Nathan and I went over the code and were able to determine this bug is the result of the handler that deletes all locks when zygrader is terminated via things like ctrl+c being called before the shared paths are properly loaded. We decided on a solution implementing a boolean in shared.py that is set to true after those paths are set, and a check to see if said boolean is set to true in the aforementioned handler.
